import Head from "next/head";
import type { NextPage } from "next";
import Header from "../components/Header";
import HeaderSection from "../components/HeaderSection";

import Features from "../components/Features";
import Categories from "../components/Categories";
import BestSellers from "../components/BestSellers";
import Testimonial from "../components/Testimonial";

import Newsletter from "../components/Newsletter";
import Footer from "../components/Footer";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Beautiful Plant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://i.pinimg.com/originals/ef/e1/e4/efe1e42892ff4a4bdd19787b56ef49c6.png" />
      </Head>
      <main className="relative mx-auto flex h-screen w-[1600px] overflow-y-scroll bg-[#FFFFFF] scrollbar-none">
        <div className="z-10 mx-[120px] mt-[40px] w-full">
          {/* header section */}
          <Header />
          <HeaderSection />
          {/* body */}
          <Features />
          <Categories />
          <BestSellers />
          <Testimonial />
          {/* footer */}
          <Newsletter />
          <Footer />
        </div>
        <div className="absolute left-0 top-0 z-0 h-[933px] w-[1106px] bg-secondaryLightGreen" />
      </main>
    </>
  );
};

export default Home;
